[package]
name = "stm32f3-liar-test"
version = "0.1.0"
authors = ["Sean Bolton <sean@smbolton.com>"]

[dependencies]
cortex-m-rt = "^0.2.3"
cortex-m = "^0.2.7"
stm32f30x = "^0.4.1"
liar = { path = "../liar-git", default-features = false }
